### ISSUE TITLE
Update blog for Tuesday-Saturday 1/13/18

### ISSUE THREAD

**Issue by MarshallMac** [FRCTeam2984/website#62]
and add pictures and stuff

**Comment by DeputyofDisorder** [comment]
The blogs themselves have been updated just need the pictures

**Comment by MarshallMac** [comment]
They should be in the Google drive

**Comment by DeputyofDisorder** [comment]
I think I already updated them from those. Thanks.


Powered by Cricket Wireless
-------- Original message --------From: MarshallMac <notifications@github.com> Date: 1/15/18  4:38 PM  (GMT-08:00) To: FRCTeam2984/website <website@noreply.github.com> Cc: DeputyofDisorder <tanvirrh1@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [FRCTeam2984/website] Update blog for Tuesday-Saturday 1/13/18
  (#62) 
They should be in the Google drive





On Jan 15, 2018 4:36 PM, "DeputyofDisorder" <notifications@github.com>

wrote:
